FROM redmine:5.1

USER root

RUN apt-get update && apt-get install -y \
  build-essential \
  libyaml-dev \
  libpq-dev \
  libmagickwand-dev \
  libmariadb-dev \
  && rm -rf /var/lib/apt/lists/*

# Optional: Kopiere entrypoint oder source code
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

USER redmine
